---
#file main.yml
- include_tasks: server.yml
  tags:
    - server

- include_tasks: agent.yml
  tags:
    - agent

- include_tasks: proxy.yml
  tags:
    - proxy

- include_tasks: sql.yml
  tags:
    - sql
