---
#file: tengine.yml
- name: Install zabbix_server environment
  hosts: test-32
  vars:
    zabbix_version: 3.4.8
    zabbix_dir: /usr/local/zabbix
    mysql_dir: /cache1/mysql
    server_port: 10001
    db_password: zabbix
    db_port: 3306

  roles: 
    - zabbix
