---
#file: tomcat restore.yml
- name: Stop {{ project }} service on remote server
  shell: /etc/init.d/tomcat-service {{ product }}-{{ project }} stop

- name: Delete current application file
  file: path={{ tomcat_dir }}/{{ product }}-{{ project }}/webapps/{{ project }} state=absent

- name: Restore application file
  command: cp -a {{ tomcat_dir }}/tmp/{{ project }} {{ tomcat_dir }}/{{ product }}-{{ project }}/webapps/

- name: Change owner for {{ project }} file
  file: path={{ tomcat_dir }}/{{ product }}-{{ project }}/webapps/{{ project }} owner=webrunner group=webrunner recurse=yes

- name: Start {{ project }} service on remote server
  shell: /etc/init.d/tomcat-service {{ product }}-{{ project }} start

- name: Pause 90s when project is em
  pause: seconds=90
  when: project == "em"
