---
#file: tomcat-project.yml
- name: Install tomcat environment
  hosts: test-31
  vars:
    product: oms
    project: em
    tomcat_dir: /cache1/web
    STOP_PORT: 8005
    RUN_PORT: 8000
    AJP_PORT: 8009
    tomcat_version: 8.5.27

  roles: 
    - tomcat
