---
#file: init.yml
#- name: Create zabbix database
#  command: ./mysql -e "create database zabbix default charset utf8;"
#  args:
#    chdir: "{{ mysql_dir }}/bin"

#- name: Add zabbix user for database
#  command: ./mysql -e "grant all on zabbix.* to zabbix@localhost identified by 'zabbix';"
#  args:
#    chdir: "{{ mysql_dir }}/bin"

- name: Excute schema sql
  command: ./mysql -uroot test -e "source /usr/local/src/zabbix-{{ zabbix_version }}/database/mysql/schema.sql"
  args:
    chdir: "{{ mysql_dir }}/bin"

#- name: Excute images sql
#  command: ./mysql -uzabbix -pzabbix zabbix < /usr/local/src/zabbix-{{ zabbix_version }}/database/mysql/images.sql
#  args:
#    chdir: "{{ mysql_dir }}/bin"

#- name: Excute data sql
#  command: ./mysql -uzabbix -pzabbix zabbix < zabbix-{{ zabbix_version }}/database/mysql/data.sql
#  args:
#    chdir: "{{ mysql_dir }}/bin"

