---
#file: main.yml
- name: Check reids-server command exists
  stat: path=/usr/local/bin/redis-server
  register: rs

- name: Copy reids compress file to remote server
  copy: src=redis-{{ redis_version }}.tar.gz dest=/usr/local/src
  when: rs.stat.exists == false

- name: Uncompress redis-{{ redis_version }}.tar.gz
  unarchive: src=/usr/local/src/redis-{{ redis_version }}.tar.gz dest=/usr/local/src/ remote_src=yes
  when: rs.stat.exists == false

- name: Install required packages of redis
  yum: state=latest name={{ item }}
  with_items:
  - make
  - gcc 
  - gcc-c++
  when: rs.stat.exists == false

- name: Compile redis source file
  make: chdir=/usr/local/src/redis-{{ redis_version }} target=install
  when: rs.stat.exists == false

- name: Delete redis source file
  file: path={{ item }} state=absent
  with_items:
  - /usr/local/src/redis-{{ redis_version }}.tar.gz
  when: rs.stat.exists == false

- name: Check {{ RUN_PORT }} directory exists
  stat: path={{ redis_dir }}/{{ RUN_PORT }}
  register: dt

- name: Create directory when {{ RUN_PORT }} directory not exists
  file: path={{ redis_dir }}/{{ RUN_PORT }} state=directory mode=0755
  when: dt.stat.exists == false

- name: Generate redis.conf
  template: src=redis.j2 dest={{ redis_dir }}/{{ RUN_PORT }}/redis.conf

- name: Change owner for {{ RUN_PORT }} file
  file: path={{ redis_dir }}/{{ RUN_PORT }} owner=nobody group=nobody recurse=yes

- name: Start redis server
  command: redis-server {{ redis_dir }}/{{ RUN_PORT }}/redis.conf
  become: true
  become_method: su
  become_user: nobody
  become_flags: '-s /bin/sh'
