---
#file: single.yml
- name: Check kafka user exists
  stat: path=/home/kafka
  register: ku

- name: Create the group kafka
  group: name=kafka state=present
  when: ku.stat.exists == false

- name: Create the user kafka
  user: name=kafka group=kafka
  when: ku.stat.exists == false

- name: Check {{ work_dir }} directory exists
  stat: path={{ work_dir }}
  register: wd

- name: Create directory when {{ work_dir }} directory not exists
  file: path={{ work_dir }} state=directory mode=0755
  when: wd.stat.exists == false

- name: Check kafka command exists
  stat: path={{ work_dir }}/kafka_{{ kafka_version }}/kafka-server-start.sh
  register: kc

- name: Copy kafka compress file to remote server
  copy: src=kafka_{{ kafka_version }}.tgz dest=/usr/local/src
  when: kc.stat.exists == false

- name: Uncompress kafka-{{ kafka_version }}.tar.gz
  unarchive: src=/usr/local/src/kafka_{{ kafka_version }}.tgz dest={{ work_dir }}/ remote_src=yes
  when: kc.stat.exists == false

- name: Create kafka necessary directory
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ dirs['data_dir'] }}"
    - "{{ dirs['conf_dir'] }}"
    - "{{ dirs['log_dir'] }}"

- name: Generate kafka configuration file
  template: src={{ item }} dest={{ dirs['conf_dir'][0] }}/
  with_items:
    - server.properties
    - log4j.properties

- name: Generate kafka.sh file
  template: src=kafka.sh dest=/etc/init.d/ mode=0755


- name: Change owner for kafka data directory
  file: path={{ item }} owner=kafka group=kafka recurse=yes
  with_items:
    - "{{ dirs['data_dir'] }}"
    - "{{ dirs['conf_dir'] }}"
    - "{{ dirs['log_dir'] }}"

- name: Start kafka service
  shell: /etc/init.d/kafka.sh start
