---
#file: redis.yml
- name: Install Redis Environment
  hosts: test-198 test-199
  vars:
    redis_version: 4.0.8
    redis_dir: /cache1/redis
    RUN_PORT: 7002
    PASSWORD: test@2018
    redis_mode: cluster

  roles: 
    - redis
